server:
  mode: dev         # 应用程序运行模式（dev开发环境、test测试环境、prod线上环境）
  host: 0.0.0.0     # 服务器IP地址，默认使用0.0.0.0
  name: orange      # 服务名称
  port: 7886       # 服务端口号
  read-timeout: 20    #读超时 单位秒 默认20
  write-timeout: 20   #写超时 单位秒 默认20
  fs-type: local    #文件服务
grpc-server:
  enable: false
  host: 0.0.0.0
  port: 7887
logger:             # 日志配置
  level: info # 级别
  prefix:    # 日志前缀
  format:  # 输出格式 json
  director: temp/logs      # 日志文件夹
  encode-level: LowercaseColorLevelEncoder # 编码级
  stacktrace-key: # 栈名
  log-in-console: true # 输出控制台
access-limit: #访问频率限制
  enable: true #是否访问限制
  duration: 5s #时长
  total: 300 #300次
jwt:                # JWT配置
  sign-key: abc   # Token密钥
  expires: 180000    # Token过期时长（单位：分钟）
  refresh: 60000    # Token 刷新时长（单位：分钟）
cache:              # 缓存配置
  type: redis #redis/memory
  addr: 127.0.0.1:6379    # Redis cluster模式以;隔开（redis本身必须是cluster模式），eg：localhost:6379;localhost:6380
  db: 5                       # 设置 DB, 只针对 `Redis Client` 和 `Failover Client`
  master-name:  #不为空 Failover模式
dbcfg: # 数据库配置
  driver: mysql  
  dsn: root:123456789@tcp(127.0.0.1:3306)/open?charset=utf8&parseTime=True&loc=Local&timeout=1000ms  # 数据库连接字符串
  log-mode: info #日志类型 GORM 定义了这些日志级别：silent、error、warn、info
  #slow-threshold: 200 #慢日志
  #max-idle-conn: 20 #最大空闲连接数 默认10
  #max-open-conn: 60 #最大打开数
  #prefix: 日志前缀
cors:
  enable: true
  mode: allow-all
  #whitelist:
  #- allow-origin: example1.com
  #  allow-methods: POST, GET
  #  allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
  #  expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
  #    Content-Type
  #  allow-credentials: true
gen: 
  enable: true #开启生成
  front-path: ../orange-admin/src
extend:           
  whileIps: 127.0.0.1
  pay-config:
    url: http://127.0.0.1:7788
    notify-url: http://127.0.0.1:86
    priKey:
    appid: "123"
    merchantNo: "123"
    currency: CNY
    prefix: YL    # SDK
  open:
    gateway-url: http://127.0.0.1:28000
    sso-url: http://127.0.0.1:18000
  ali-oss:
    endpoint: https://oss-hangzhou.aliyuncs.com
    access-key-id: 123
    access-key-secret: 123
    bucket-name: abc
    base-path: pictures
    bucket-url: https://super-chrome.oss-hangzhou.aliyuncs.com
  rd-config:
    enable: false
    driver: consul
    endpoints:
      - 127.0.0.1:8500
    scheme: http
    timeout: 5s
    registers:
      - id:  #127.0.0.1:7888
        protocol: http
        #name: orange-app
        #addr: 127.0.0.1
        #port: 7888
        #health-check: http://127.0.0.1:7888/api/health
        #tags:
        #  - "dev"
        #interval: 5s
        #timeout: 10s
      - id:  #127.0.0.1:7889
        protocol: grpc
        #name: orange-app-grpc
        #addr: 127.0.0.1
        #port: 7889
        #health-check: 127.0.0.1:7889/Health
        #tags:
        #  - "dev"
        #interval: 5s
        #timeout: 10s
    discoveries:
      - name: name
        enable: false
        fail-limit: 3
  ding: 
    agent-id:
    app-key:
    app-secret:
    crop-id:
  wechat-mp:
    app-id: 
    app-secret: 
    wx-token: 
    encoding-aes-key: 
  ai:
    ali:
      sk: 

    